CSP-1418: PR Inner API: Create Permission Request
SkillsFundingAgency/das-pr-api pull request #51
Opened 2024-07-24 15:34 UTC by shaun-downey-education

- Create Permission Request endpoint and associated handler.

2024-07-25 08:14 UTC, DevenKShah requested changes

2024-07-25 08:14 UTC, DevenKShah commented on src/SFA.DAS.PR.Application/Requests/Commands/CreatePermissionRequest/CreatePermissionRequestCommandValidator.cs
> +        RuleFor(a => new RequestValidationObject() { Ukprn = a.Ukprn, AccountLegalEntityId = a.AccountLegalEntityId })
Additionally we need to check that a record exists in `AccountProviderLegalEntities` table.

2024-07-25 08:44 UTC, DevenKShah commented on src/SFA.DAS.PR.Application/Requests/Commands/CreatePermissionRequest/CreatePermissionRequestCommandValidator.cs
> +        RuleFor(a => a.Operations).ValidateOperationCombinations();
The combination message for the operations, needs a little bit of improving as the comma delimiter is used between and within combinations.

2024-07-29 13:57 UTC, PeterDavidWilliams submitted a review, later dismissed

2024-08-30 15:30 UTC, closed without merging