CSP-1525: Accept Add Account Request
SkillsFundingAgency/das-pr-api pull request #68
Opened 2024-09-06 13:22 UTC by shaun-downey-education

- New controller method in the **RequestsController** for **AcceptAddAccountRequest**.
- Added **AcceptAddAccountRequestCommand** with associated validation and handler.

2024-09-06 14:40 UTC, MarkFCain approved these changes

2024-09-09 08:22 UTC, DevenKShah requested changes

2024-09-09 08:22 UTC, DevenKShah commented on src/SFA.DAS.PR.Application/Requests/Commands/AcceptAddAccountRequest/AcceptAddAccountRequestCommandHandler.cs
> +        AccountProviderLegalEntity accountProviderLegalEntity =
There are chances that the APLE does not exist as it is `Add Employer` journey

2024-09-09 08:22 UTC, DevenKShah commented on src/SFA.DAS.PR.Application/Requests/Commands/AcceptAddAccountRequest/AcceptAddAccountRequestCommandHandler.cs
> +            Action = nameof(RequestAction.AccountAdded),
Can the action be converted in to a Enum type?

2024-09-13 12:34 UTC, DevenKShah commented on src/SFA.DAS.PR.Application/Permissions/Commands/PostPermissions/PostPermissionsCommandHandler.cs
The naming is unconventional, if this adds/updates permission, we can use `UpsertPermissionsCommand`

2024-09-13 13:26 UTC, DevenKShah approved these changes

2024-09-19 12:58 UTC, debrr07 approved these changes

2024-09-19 13:50 UTC, merged